---
# yamllint configuration
# See: https://yamllint.readthedocs.io/en/stable/rules.html

extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Allow truthy values (yes/no, on/off, etc.)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Indentation settings
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow document start marker to be optional
  document-start: disable

  # Comments
  comments:
    min-spaces-from-content: 1

ignore: |
  node_modules/
  .git/
